### ISSUE TITLE
Maven error: invalid target release

### ISSUE THREAD

**Issue by wwwjames** [relenteny/microservice#1]
Getting `Maven error: invalid target release`, to fix I replaced maven.compiler.release with maven.compiler.source and maven.compiler.target. : 

diff --git a/microservice-platform-bom/pom.xml b/microservice-platform-bom/pom.xml
index d492746..fea2a54 100644
--- a/microservice-platform-bom/pom.xml
+++ b/microservice-platform-bom/pom.xml
@@ -24,7 +24,8 @@
     <maven.surefire-plugin.version>2.22.1</maven.surefire-plugin.version>
     <maven.failsafe-plugin.version>2.22.1</maven.failsafe-plugin.version>
     <maven.compiler.parameters>true</maven.compiler.parameters>
-    <maven.compiler.release>8</maven.compiler.release>
+    <maven.compiler.source>1.8</maven.compiler.source>    
+    <maven.compiler.target>1.8</maven.compiler.target>    
     <maven.source-plugin.version>3.2.1</maven.source-plugin.version>
     <maven.javadoc-plugin.version>3.1.1</maven.javadoc-plugin.version>

**Comment by relenteny** [comment]
I may have to update the POM to support profiles. I'm using JDK 11, and the existing POMs do work. I' using JDK11 as Quarkus will support JDK11 for both building JARs and native executables. Right now, while Quarkus supports JDK11 for JARs, it doesn't support it for native executables.

How does a new profile sound that can be set based on JDK version? Maven does support this. You wouldn't have to set a profile flag. It would just detect it when Maven was executed.

**Comment by relenteny** [comment]
@wwwjames, I just commited a change that accommodates having either JDK 8 or 11. Thanks for catching this.

I will be tagging this as release 1.0. With the just announced release of Quarkus 1.2.0, I'll be updating the project to require JDK 11.
